<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://example.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://org.apache.axis2/xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" targetNamespace="http://example.com">
    <wsdl:types>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://example.com">
            <xs:element name="getAireTriangle">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="hauteur" type="xs:int"/>
                        <xs:element name="base" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getAireTriangleResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="return" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getAireRectangle">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="largeur" type="xs:int"/>
                        <xs:element name="hauteur" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getAireRectangleResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="return" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getAireCarre">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="longeur" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="getAireCarreResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="return" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="getAireCarreRequest">
        <wsdl:part name="parameters" element="ns:getAireCarre"/>
    </wsdl:message>
    <wsdl:message name="getAireCarreResponse">
        <wsdl:part name="parameters" element="ns:getAireCarreResponse"/>
    </wsdl:message>
    <wsdl:message name="getAireRectangleRequest">
        <wsdl:part name="parameters" element="ns:getAireRectangle"/>
    </wsdl:message>
    <wsdl:message name="getAireRectangleResponse">
        <wsdl:part name="parameters" element="ns:getAireRectangleResponse"/>
    </wsdl:message>
    <wsdl:message name="getAireTriangleRequest">
        <wsdl:part name="parameters" element="ns:getAireTriangle"/>
    </wsdl:message>
    <wsdl:message name="getAireTriangleResponse">
        <wsdl:part name="parameters" element="ns:getAireTriangleResponse"/>
    </wsdl:message>
    <wsdl:portType name="CalculateurAireServicePortType">
        <wsdl:operation name="getAireCarre">
            <wsdl:input message="ns:getAireCarreRequest" wsaw:Action="urn:getAireCarre"/>
            <wsdl:output message="ns:getAireCarreResponse" wsaw:Action="urn:getAireCarreResponse"/>
        </wsdl:operation>
        <wsdl:operation name="getAireRectangle">
            <wsdl:input message="ns:getAireRectangleRequest" wsaw:Action="urn:getAireRectangle"/>
            <wsdl:output message="ns:getAireRectangleResponse" wsaw:Action="urn:getAireRectangleResponse"/>
        </wsdl:operation>
        <wsdl:operation name="getAireTriangle">
            <wsdl:input message="ns:getAireTriangleRequest" wsaw:Action="urn:getAireTriangle"/>
            <wsdl:output message="ns:getAireTriangleResponse" wsaw:Action="urn:getAireTriangleResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CalculateurAireServiceSoap11Binding" type="ns:CalculateurAireServicePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <wsdl:operation name="getAireCarre">
            <soap:operation soapAction="urn:getAireCarre" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="getAireRectangle">
            <soap:operation soapAction="urn:getAireRectangle" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="getAireTriangle">
            <soap:operation soapAction="urn:getAireTriangle" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="CalculateurAireServiceSoap12Binding" type="ns:CalculateurAireServicePortType">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <wsdl:operation name="getAireCarre">
            <soap12:operation soapAction="urn:getAireCarre" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="getAireRectangle">
            <soap12:operation soapAction="urn:getAireRectangle" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="getAireTriangle">
            <soap12:operation soapAction="urn:getAireTriangle" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="CalculateurAireServiceHttpBinding" type="ns:CalculateurAireServicePortType">
        <http:binding verb="POST"/>
        <wsdl:operation name="getAireCarre">
            <http:operation location="getAireCarre"/>
            <wsdl:input>
                <mime:content type="application/xml" part="parameters"/>
            </wsdl:input>
            <wsdl:output>
                <mime:content type="application/xml" part="parameters"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="getAireRectangle">
            <http:operation location="getAireRectangle"/>
            <wsdl:input>
                <mime:content type="application/xml" part="parameters"/>
            </wsdl:input>
            <wsdl:output>
                <mime:content type="application/xml" part="parameters"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="getAireTriangle">
            <http:operation location="getAireTriangle"/>
            <wsdl:input>
                <mime:content type="application/xml" part="parameters"/>
            </wsdl:input>
            <wsdl:output>
                <mime:content type="application/xml" part="parameters"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CalculateurAireService">
        <wsdl:port name="CalculateurAireServiceHttpSoap11Endpoint" binding="ns:CalculateurAireServiceSoap11Binding">
            <soap:address location="http://localhost:8080/axis2/services/CalculateurAireService"/>
        </wsdl:port>
        <wsdl:port name="CalculateurAireServiceHttpSoap12Endpoint" binding="ns:CalculateurAireServiceSoap12Binding">
            <soap12:address location="http://localhost:8080/axis2/services/CalculateurAireService"/>
        </wsdl:port>
        <wsdl:port name="CalculateurAireServiceHttpEndpoint" binding="ns:CalculateurAireServiceHttpBinding">
            <http:address location="http://localhost:8080/axis2/services/CalculateurAireService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
